version: '3.7'
services:
  bot:
    image: 'python:latest'
    container_name: 'bot'
    restart: always
    volumes:
      - './bot:/bot'
    working_dir: '/bot'
    command: 'pip3 install -r requirements.txt && python3 main.py'
  db:
    image: 'postgres:latest'
    container_name: 'db'
    restart: always
    volumes:
      - './db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
